<?php
function ahah_demo_menu() {
  $items = array();

  $items['ahah-demo'] = array(
    'title' => 'AHAH Select Dropdowns Demo',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ahah_demo_form'),
    'access arguments' => array('access content'),
  );

  return $items;
}

function ahah_demo_form($form_state) {
  $form = array();

  ahah_helper_register($form, $form_state);

  $department = get_department_from_select($form_state);

  add_search_wrapper_to($form);

  add_department_select_to($form, $department);
  add_department_update_button_for_no_js_to($form);

  if (we_have_department_info($department)) {
    $category = get_category_from_select($form_state);
    add_category_elements_to($form, $department, $category);

    run_checks_on($department, $form_state);

    put_department_in_form_storage($department, $form_state);

    if(we_have_category_info($form_state)) {
      add_model_element_to($form, $form_state);
    }

  } else {
    ensure_no_trailing_model_select($form_state);
  }

  add_submit_button_to($form);

  return $form;
}

function get_department_from_select($form_state) {
  if (!isset($form_state['storage']['search']['department'])) {
    return 'none';
  }
  else {
    return  $form_state['storage']['search']['department'];
  }
}

function add_search_wrapper_to(&$form) {
  $form['search'] = array(
    '#tree' => TRUE,
    '#type' => 'fieldset',
    '#title' => 'Search',
    '#prefix' => '<div id="search-wrapper">',
    '#suffix' => '</div>',
  );
}

function add_department_select_to(&$form, $department) {
  $form['search']['department'] = array(
    '#type' => 'select',
    '#title' => 'Select Department',
    '#options' => ahah_demo_get_departments(),
    '#ahah' => array(
      'path' => ahah_helper_path(array('search')),
      'wrapper' => 'search-wrapper',
      'method' => 'replace',
    ),
    '#default_value' => $department,
  );
}

function ahah_demo_get_departments() {
  $departments = array();
  $departments['none'] = t('Please select');

  $departments['1'] = 'Compaction';
  $departments['2'] = 'Concrete Masonry';
  $departments['3'] = 'Earthmoving';
  $departments['4'] = 'General Equipment';
  $departments['5'] = 'Heaters';

  return $departments;
}

function add_department_update_button_for_no_js_to(&$form) {
  $form['search']['update_department'] = array(
    '#type'  => 'submit',
    '#value' => t('Update department'),
    // Note that we can simply use the generic submit callback provided by the
    // ahah_helper module here!
    // All it does, is set $form_state['rebuild'] = TRUE.
    '#submit' => array('ahah_helper_generic_submit'),
    // We set the 'no-js' class, which means this submit button will be hidden
    // automatically by Drupal if JS is enabled.
    '#attributes' => array('class' => 'no-js'),
  );
}

function we_have_department_info($department) {
  return $department != 'none';
}

function get_category_from_select($form_state) {
  return $form_state['storage']['search']['category_wrapper']['category'];
}

function add_category_elements_to(&$form, $department, $category) {
  add_category_wrapper_to($form);
  add_category_select_to($form, $department, $category);
}

function add_category_wrapper_to(&$form) {
  $form['search']['category_wrapper'] = array(
    '#type' => 'fieldset',
    '#tree' => TRUE,
    '#title' => 'Search Category & Model',
    '#prefix' => '<div id="category-wrapper">',
    '#suffix' => '</div>',
  );
}

function add_category_select_to(&$form, $department, $category) {
  $form['search']['category_wrapper']['category'] = array(
    '#type' => 'select',
    '#title' => 'Select Category',
    '#options' => ahah_demo_get_categories($department),
    '#ahah' => array(
      'path' => ahah_helper_path(array('search', 'category_wrapper')),
      'wrapper' => 'category-wrapper',
      'method' => 'replace',
    ),
    '#default_value' => $category,
  );
}

function get_stored_department_from($form_state) {
  return $form_state['storage']['dept_cache'];
}

function ahah_demo_get_categories($dept) {
  $categories = array();
  $categories['none'] = t('Please select');

  switch($dept) {
    case 1:
      $categories[6] = 'Tamper';
      $categories[7] = 'Trench Compactor';
      $categories[8] = 'Reversible Plate Compactor';
      break;
    case 2:
      $categories[9] = 'Concrete Bucket';
      $categories[10] = 'Masonry Saws';
      $categories[11] = 'Mortar Mixers';
      break;
    case 3:
      $categories[12] = 'Backhoe Loaders';
      $categories[13] = 'Excavators';
      $categories[14] = 'Skid Steers';
      break;
    case 4:
      $categories[15] = 'Chain Saws';
      $categories[16] = 'Sanders';
      $categories[17] = 'Wrenches';
      break;
    case 5:
      $categories[18] = 'Electric Heaters';
      $categories[19] = 'Kerosene Heaters';
      $categories[20] = 'Propane Heaters';
      break;
  }

  return $categories;
}

function run_checks_on($department, &$form_state) {
  $stored_department = get_stored_department_from($form_state);
  if (department_has_changed($stored_department, $department)) {
    ensure_no_trailing_model_select($form_state);
  }
}

function department_has_changed($stored_value, $current_value) {
  return $stored_value != $current_value;
}

function ensure_no_trailing_model_select(&$form_state) {
  $form_state['storage']['search']['category_wrapper'] = NULL;
}

function put_department_in_form_storage($department, &$form_state) {
  $form_state['storage']['dept_cache'] = $department;
}

function we_have_category_info($form_state) {
  return
    isset($form_state['storage']['search']['category_wrapper']['category']) &&
    $form_state['storage']['search']['category_wrapper']['category'] != 'none';
}

function add_model_element_to(&$form, $form_state) {
  $form['search']['category_wrapper']['model'] = array(
    '#type' => 'select',
    '#title' => 'Select Model',
    '#options' => ahah_demo_get_models($form_state['storage']['search']['category_wrapper']['category']),
    '#default_value' => "default",
  );
}

function ahah_demo_get_models($cat) {
  $models = array();
  $models['none'] = t('Please select');

  switch ($cat) {
    case 6:
      $models[19] = 'Tamper 2000';
      $models[20] = 'Tamper 4000';
      break;
    case 7:
      $models[21] = 'Trencher 2000';
      $models[22] = 'Trencher 4000';
      break;
    case 8:
      $models[23] = 'Plate 2000';
      $models[24] = 'Plate 4000';
      break;
    case 9:
      $models[25] = 'Bucket A';
      $models[26] = 'Bucket B';
      break;
    case 10:
      $models[27] = 'Saw 2000';
      $models[28] = 'Saw 4000';
      break;
    case 11:
      $models[29] = 'Mixer 2000';
      $models[30] = 'Mixer 4000';
      break;
    case 12:
      $models[31] = 'Bachkoe 2000';
      $models[32] = 'Bachkoe 4000';
      break;
    case 13:
      $models[33] = 'Excavator 2000';
      $models[34] = 'Excavator 4000';
      break;
    case 14:
      $models[35] = 'Skid Steer 2000';
      $models[36] = 'Skid Steer 4000';
      break;
    case 15:
      $models[37] = 'Chain Saw 2000';
      $models[38] = 'Chain Saw 4000';
      break;
    case 16:
      $models[39] = 'Sander 2000';
      $models[40] = 'Sander 4000';
      break;
    case 17:
      $models[41] = 'Wrench 2000';
      $models[42] = 'Wrench 4000';
      break;
    case 18:
      $models[43] = 'Electric 2000';
      $models[44] = 'Electric 4000';
      break;
    case 19:
      $models[43] = 'Kerosene 2000';
      $models[44] = 'Kerosene 4000';
      break;
    case 20:
      $models[43] = 'Propane 2000';
      $models[44] = 'Propane 4000';
      break;
  }

  return $models;
}

function add_submit_button_to(&$form) {
  $form['save'] = array(
    '#type'  => 'submit',
    '#value' => t('See available equipment'),
  );
}

function ahah_demo_form_submit($form, $form_state) {
  $model_id = $form_state['values']['search']['category_wrapper']['model'];
  drupal_set_message("Your model is: $model_id");

  $category_id = $form_state['values']['search']['category_wrapper']['category'];
  drupal_set_message("Your category is: $category_id");

  $department_id = $form_state['values']['search']['department'];
  drupal_set_message("Your department is: $department_id");
}
