<?php
/** Implementation of hook_menu()
  */
function ahah_demo_menu() {
  $items = array();

  $items = array(
    'title' = 'AHAH Select Dropdowns Demo',
    'page callback' = 'drupal_get_form',
    'page arguments' = array('ahah_demo_form'),
    'access arguments' = array('access content'),
  );
}

/** Form defintion
  */
function ahah_demo_form($form_state) {
  $form = array();

  return $form;
}
